language: scala
script: sbt -jvm-opts jvmopts.travis -D test
jdk:
- oraclejdk8
notifications:
  flowdock:
    secure: j3YP9TjiIcMRy2mvunF1AHBOFnz2H7mZAFVbHPBNkAjMCwSdBNvLpn33qv6ybr02c5snBDJTs0P70RJ/mh3YsqwnIeloQD9HUfnndKQD6ujxx1QWRI/lVDW4pfVRQEuPsXdW/3AiqxrSG5BS4thiyc3vj3LpnodHwNMUT+Nlmq0=
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-sphinx
services:
  - postgresql
before_script:
  - sleep 15
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
